---
title: "BNN paper outline"
author: "Arnie Seong"
date: "Last updated: `r format(Sys.time(), '%d %B %Y')`"
header-includes:
  - \usepackage{bm}
  - \usepackage{xcolor}
  - \usepackage{amssymb}
output: 
  html_document:
    df_print: paged
    theme: cerulean
    highlight: tango
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_fold: show
urlcolor: blue
params:
  retrain: FALSE
  seed: 314
editor_options: 
  chunk_output_type: console
---


<style type="text/css">

  #TOC>ul>li, h1, h2{
    font-weight: bold;
  }
  
  blockquote{
    background-color: #d5f2f5;
    font-size: small;
  }
  
  b, strong {
   color: #11579e;
  }
  
  caption {
    color: #11579e;
    font-weight: bold;
    font-size: 1.0em;
  }
  
  h1 { font-size: 2em }
  h2 { font-size: 1.6em  }
  h3 { font-size: 1.25em }
  h4 { font-size: 1.10em }
  h5, h6 { font-size: 1em    }
  
  h1, h2, h3 {font-weight: bold;}
  
  a {font-weight: bold; text-decoration: underline}
  
  .nav-pills>li>a:hover, 
  .nav-pills>li>a:focus, 
  .nav-pills>li.active>a,     
  .nav-pills>li.active>a:hover, 
  .nav-pills>li.active>a:focus{
     background-color: #11579e;
  }
  
  .nav-pills{
     background-color: #d5f2f5;
  }
</style>









# Intro:

- Neural networks as powerful prediction systems, and Bayesian networks for stochastic functions.  
  - Bayesian networks difference from regular (learn distribution of weights, allow for uncertainty quantification)
  - Ghosh & Doshi-Velez 2017/2019 paper on model selection - "By treating the weights in a neural network as random varialbes and performing posterior inference on these weights, BNNs can avoid overfitting in the regime of small data, provide well-calibrated posterior uncertainty estimates, and model a large class of stochastic functions with heteroskedastic and multimodal noise."

- combine with some remarks on dataset used

- My method's contributions:

  - modify LUW 2017's procedure for application to input variable selection / feature selection, combining several desirable characteristics: statistically principled variable selection, higher interpretability, while maintaining predictive accuracy.

  - procedure for BFDR control in a horseshoe NN, show empirically that it approaches nominal FDR (future work needed on theory)

  - possible path for mitigating identifiability issues for parameters in Bayesian neural networks which arise from the composition of affine functions via composite spectral norm (future work needed on theory)


# Related work:

## Selection in NNs:

- Almost all literature on selection in neural networks focuses only on sparsifying the neural network architecture itself, without much if any regard to input feature selection.

  - Different variations of dropout (randomly pruning inputs and layer units during training) has long been used to prevent overfitting in deterministic NNs; Gal & Gahramani 2016 - Dropout as a Bayesian Approximation - show that dropout corresponds to an approximate variational distribution.

  - Louizos, Ullrich, Welling 2017 "Bayesian Compression" - which we draw most heavily from.  Their focus is on a grouped scale mixture prior, providing code for a Normal Jeffrey's prior.  Their method was motivated by the desire to compress neural network sizes, so focuses on pruning hidden units and using shorter bit-length representations of weights ("quantization") while preserving predictive accuracy.

  - Rockova & Polson 2017 provide theory on posterior selection consistency of _model architectures_ in Bayesian spike-and-slab NNs with RELU activations.  

  - Ghosh & Doshi-velez 2017/2019 model selection - prune _units_ with horseshoe, i.e. selection of number of neurons in each layer, not on input variables.
    - selection based on thresholding

  - Skaaret-Lund, Storvik, Hubin 2023 (related work from Hubin Storvik in 2019, 2023)- propose latent binary bayesian neural network (LBBNN) - use spike-and-slab with latent variables to model dependencies between weights; variational inference procedure enhanced with inverse autoregressive flow (type of normalizing flow)

  - Theory on posterior consistency for model selection from Rockova and polson, Wang and Rockova, but again the focus is on selecting the number of units in NN layers  

- When variable selection is the actual focus, input sparsity / variable selection is still typically treated heuristically.  Of the very small handful of works that focus specifically on input feature selection:

  1. an ArXiv paper Overweg Popkes 2019 "Interpretable outcome prediction with sparse bayesian neural networks in intensive care" - similar approach, but variable selection is still largely heuristic, based on thresholding

  2. Liu 2021: Variable Selection with Rigorous Uncertainty Quantification using Deep Bayesian Neural Networks: Posterior Concentration and Bernstein-von Mises Phenomenon - variable selection performed by checking if credible interval for variable importance measure (L2 norm of gradient function, i.e. partial derivative signifying change in f(\vec{x}_i) over change in x_p) contains 0, justified by developing BvM theorem regarding variable importance measure (posterior of VIM converges to Gaussian, 1 - alpha credible interval has 1-alpha coverage).  Does not use priors specifically developed for sparsity (uses standard iid Gaussian priors for model weights).


  3. Liang et al 2018 Bayesian Neural Networks for Selection of Drug Sensitive Genes - 

    - 1 hidden layer, relatively small dimension (i.e. all results are from NNs with 3, 5, 7 units in hidden layer, chosen empirically after short MC run to minimize an information criterion - they use EBIC, but suggest BIC and AIC also work)  

    - selection performed over every single network connection --- authors assert that this offers some interpretability; Sure, but probably only in a single hidden layer network, or v. small / v. sparse architectures.  

    - population stochastic approximation monte carlo sampling - run short stochastic approximation MC chains in parallel by sharing information on a working parameter that penalizes over-visited regions and rewards under-visited regions to help system escape local extrema


# Spike-and-slab & scale mixtures

- Scale mixtures as relaxed version of spike-slab (bernoulli computation explodes dimensionality and is thus costly) 

- LUW 2017 use the Normal-Jeffrey's, but Hron et al 2009(?) show that the improper prior induces pathologies related to the VI approximation

## Horseshoe prior 
- posterior consistency, BMA-like properties for prediction, shrinkage factor $\kappa_j = (1 + \lambda_j^2 \tau^2)^{-1}$ and $1 - \kappa_j$ as "pseudo" PIPs (Carvalho 2009?)

- posterior consistency for architecture selection (Rockova Polson 2017?)




# Variational Inference

- VI used instead of costly MCMC; discussions from LUW 2017 and Ghosh & Doshi-Velez provide a quick overview

- Mean Field VI - 
  - fast, easy to compute if VI distributions are fully factorized / independent
  - some evidence that network depth can overcome the independence in the VI formulation (Farquhar Smith Gal 2020 Try Depth instead of weight correlations....)
  - limitations:
    - approximation is limited by variational distributions.  Log-Normal dist'n probably not the best; could possibly be improved by using normalizing flows as in Skaaret-lund & Storvik
    - Ghosh and Doshi-Velez 2019 address some of these by placing a MVN prior on weights, but not implemented here

## KL divergence and ELBO

- pick up on discussion from intro



# Methods

## Bayesian formulation of model

- important point here is the grouped structure

## Variational distributions 

  - uncentered parameterization in the vein of (LUW 2017, Ghosh & Doshi-Velez)
  - Rezende local reparametrization trick

### KLs (or in appendix)

## Correction to global scale parameter

- composite spectral norm as (an approximate) solution to identifiability of global scale param across layers

  - approximate because of RELU activations, effect of bias parameters

- why not just use hshoe only in first layer, since inference on variable selection basically depends on first layer?  Because hshoe on inputs to 2nd layer induces unit sparsity in 1st layer --- indicates which nodes from the first layer are unimportant thus providing "representation" sparsity in first layer and mitigating identifiability issues resulting from having multiple first hidden layer units.
  - Liang et al 2018 approach this issue in a different way, by treating the number of nodes in the hidden layer as a parameter which they tune manually (as described above)






# Experiments

## nonlinear function recovery

- in general, when the number of observations is near to or exceeds the number of network parameters, nonlinear function recovery is good

- individual functions are not centered --- each of the f_j's ends up with its own intercept and thus are unidentifiable.  There are some additional ways to combat this (running tests)


## variable selection & competitors based on Liang & Li 2018 synthetic simulations

- use BART, spikeslab gam (specifying needed interactions and not), add softbart
- could include lm, LASSO, regular spike-slab (linear) but these are straw men (do incredibly poorly)


## salary data


