---
title: "Simulation results, incremental mdoel changes"
author: "Arnie Seong"
date: "`r format(Sys.time(), '%d %B %Y')`"
header-includes:
  - \usepackage{bm}
  - \usepackage{xcolor}
  - \usepackage{amssymb}
output: 
  html_document:
    df_print: paged
    theme: cerulean
    highlight: tango
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true
    code_fold: show
urlcolor: blue
params:
  retrain: FALSE
  seed: 314
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE, message=F, echo=F, warning=F}
# LIBRARIES----

#### plotting:
library(ggplot2)
library(gridExtra)

# #### Misc:
library(here)
library(tidyr)
library(knitr)
library(kableExtra)
library(dplyr)

# model packages
library(torch)

# DOCUMENT SETUP ----
# detect pdf/html output, set chunk options, sci.notation 
latex_out <- knitr::is_latex_output()
knitr::opts_chunk$set(
  cache = FALSE, 
  message = FALSE, 
  echo = !knitr::is_latex_output(), 
  warning = FALSE
)


if (knitr::is_latex_output()) {
  knitr::opts_chunk$set(fig.height=4, 
                        fig.width=6)
} else {
  knitr::opts_chunk$set(out.width = "100%")
}

options(scipen=10)


# TEXT/TABLE FORMATTING----

custom_purple <- ifelse(
  knitr::is_latex_output(),
  "purple",
  "#b51ced"
)

custom_blue <- ifelse(
  knitr::is_latex_output(),
  "blue",
  "#11579e"
)

colorize <- function(x, color=custom_purple) {
  # text color conditional on latex/html output
  # from rmarkdown cookbook
  if (knitr::is_latex_output()) {
    sprintf("\\textcolor{ %s}{ %s}", color, x)
  } else if (knitr::is_html_output()) {
    sprintf("<span style='color: %s;'>%s</span>", color, x)
  } else x
}

cat_color <- function(txt, style = 1, color = 36){
  cat(
    paste0(
      "\033[0;",
      style, ";",
      color, "m",
      txt,
      "\033[0m","\n"
    )
  )  
}

# kable NA handling
options(knitr.kable.NA = '')

# mykable function
mykable <- function(tab, cap,
                    latex_options=c("hold_position", "scale_down", "striped"), 
                    bootstrap_options=c("striped", "hover", "condensed"), 
                    full_width=F, position="center", ...){
  # kable formatting conditional on latex or html output
  if (is.null(getOption("knitr.in.progress"))){
    print(tab)
  } else if (knitr::is_latex_output()){
    kable(x=tab, caption=cap, ...) %>%
      kableExtra::kable_styling(latex_options = latex_options)
  } else if (knitr::is_html_output()){
    kable(x=tab, caption=cap, ...) %>%
      kableExtra::kable_styling(bootstrap_options = bootstrap_options, full_width=full_width, position=position)
  }
}

# notin
`%notin%` <- Negate(`%in%`)

source(here("Rcode", "torch_horseshoe_klcorrected.R"))
source(here("Rcode", "sim_functions.R"))
source(here("Rcode", "analysis_fcns.R"))
```





# original function set

```{r FNAMES_SETUP, echo = FALSE}
img_suffixes <- c(paste0("_e", 1:9, "e_+05.png"), "_e1e_+06.png")

stem_orig <- here::here("sims", "results", "fcnl_hshoe_mod_12500obs_")
seed_orig <- c(966694, 191578, 272393, 718069, 377047)
resfile_orig <- paste0(stem_orig, seed_orig, ".RData")
modfile_orig <- paste0(stem_orig, seed_orig, ".pt")
```




```{r}
load(resfile_orig[1])
plot_datagen_fcns(sim_res$sim_params$flist)
```




## 2 hidden layers, 16-8 {.tabset .tabset-pills}

- uncorrected KL, without Kaiming initialization, $\tau_0 = 1$


### sim 1

```{r VIS_CHUNK}
loss_pltfcn(sim_res, burn = 2e4)$mse_plt
loss_pltfcn(sim_res, burn = 2e4)$kl_plt

varmat_pltfcn(
  sim_res$alpha_mat,
  y_name = "alpha",
  burn = 0
)$all_vars_plt

varmat_pltfcn(
  sim_res$alpha_mat,
  y_name = "alpha",
  burn = 25e4
)$all_vars_plt


kmat_global <- kappamat_from_sim_res(sim_res)
kmat_local <- kappamat_from_sim_res(sim_res, type = "local")
varmat_pltfcn(
  kmat_global,
  y_name = "GLOBAL kappa",
  burn = 0
)$all_vars_plt

varmat_pltfcn(
  kmat_local,
  y_name = "LOCAL kappa",
  burn = 0
)$all_vars_plt

err_by_max_bfdr(kmat_local[nrow(kmat_local), ]) + 
  labs(
    subtitle = "using local kappas as dropout probabilities"
  )
err_by_max_bfdr(kmat_global[nrow(kmat_global), ]) + 
  labs(
    subtitle = "using global kappas as dropout probabilities"
  )

```

### sim 2

```{r}
load(resfile_orig[2])
<<VIS_CHUNK>>
```


### sim 3

```{r}
load(resfile_orig[3])
<<VIS_CHUNK>>
```

### sim 4

```{r}
load(resfile_orig[4])
<<VIS_CHUNK>>
```

### sim 5

```{r}
load(resfile_orig[5])
<<VIS_CHUNK>>
```




# smoother function set

```{r}

```

